### ISSUE TITLE
Fail to get schema of a tag

### ISSUE THREAD

**Issue by mostafabarmshory** [pluf/shop#7]
Here is the error:

    <br />
    <b>Fatal error</b>:  Uncaught Error: Class 'Shop_Tags' not found in /var/www/vendor/pluf/core/src/Pluf/Views.php:594
    Stack trace:
    #0 /var/www/vendor/pluf/core/src/Pluf/Dispatcher.php(269): Pluf_Views-&gt;getSchema(Object(Pluf_HTTP_Request), Array,     Array)
    #1 /var/www/vendor/pluf/core/src/Pluf/Dispatcher.php(183): Pluf_Dispatcher::send(Object(Pluf_HTTP_Request), Array, Array)
    #2 /var/www/vendor/pluf/core/src/Pluf/Dispatcher.php(95): Pluf_Dispatcher::match(Object(Pluf_HTTP_Request))
    #3 /var/www/html/index.php(9): Pluf_Dispatcher::dispatch('/api/v2/shop/ta...', Array)
    #4 {main}
          thrown in <b>/var/www/vendor/pluf/core/src/Pluf/Views.php</b> on line <b>594</b><br />
`

And the REST API:

    http://localhost:9001/api/v2/shop/tags/schema

**Comment by hadimansouri** [comment]
It is fixed already. See [issue-6](https://github.com/pluf/shop/issues/6).
We have to wait for the next release.
